name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  push:
    branches: [main]

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OSV Scanner
      run: |
        curl -sSL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64.tar.gz | tar xz -C /usr/local/bin
        chmod +x /usr/local/bin/osv-scanner-linux-amd64
        mv /usr/local/bin/osv-scanner-linux-amd64 /usr/local/bin/osv-scanner

    - name: Run OSV Scanner
      run: osv-scanner -o osv-scan-results.sarif .

    - name: Upload OSV SARIF report to Security Dashboard
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./osv-scan-results.sarif
