name: Daily Security Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  push:
    branches: [main]

jobs:
  DependenciesAnalysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run OSV Scanner
      uses: google/osv-scanner-action/osv-scanner-action@v1
      # Optional inputs can be added here if needed

    - name: Upload OSV SARIF report to Security Dashboard
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./osv-scan-results.sarif

