name: Security Check on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  osv-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base commit (PR base)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Run OSV Scanner on base code
        uses: google/osv-scanner-action/osv-scanner-action@v1
        id: base-scan
        with:
          format: sarif
          output: base-scan-results.sarif
          scan-path: app/

      - name: Checkout PR commit (head)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run OSV Scanner on PR code
        uses: google/osv-scanner-action/osv-scanner-action@v1
        id: pr-scan
        with:
          format: sarif
          output: pr-scan-results.sarif
          scan-path: app/

      - name: Compare OSV Scanner results
        uses: google/osv-scanner-action/osv-reporter-action@v1
        id: compare
        with:
          base-report: base-scan-results.sarif
          pr-report: pr-scan-results.sarif
          output: diff-report.sarif

      - name: Upload OSV differential report artifact
        uses: actions/upload-artifact@v3
        with:
          name: osv-differential-report
          path: diff-report.sarif

  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout base commit (PR base)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Save baseline commit hash
        id: baseline
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout PR commit (head)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Semgrep differential analysis
        run: |
          semgrep --config p/java --baseline-commit ${{ steps.baseline.outputs.commit }} --json > semgrep-report.json

      - name: Upload Semgrep differential report artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-differential-report
          path: semgrep-report.json

